/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.telas;


import br.com.senac.objects.Product;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandre S. Negrão
 */
public class ProductMain extends javax.swing.JFrame {

    private Product prod;

    public ProductMain() { 
        initComponents();
        this.setLocationRelativeTo(null);
        butAlterar.setVisible(false);
        butExcluir.setVisible(false);
    }

    /**
     * Creates new form Produto
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlabelNome = new javax.swing.JLabel();
        nomeText = new javax.swing.JTextField();
        jlabelQuantidade = new javax.swing.JLabel();
        jlabelColecao = new javax.swing.JLabel();
        jlabelSexo = new javax.swing.JLabel();
        butCadastrar = new javax.swing.JButton();
        butAlterar = new javax.swing.JButton();
        butExcluir = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        precoText = new javax.swing.JTextField();
        qtdText = new javax.swing.JTextField();
        jlabelQuantidade1 = new javax.swing.JLabel();
        qtdText1 = new javax.swing.JTextField();
        qtdText2 = new javax.swing.JTextField();
        qtdText3 = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Produto");

        jlabelNome.setText("*Nome:");

        nomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextActionPerformed(evt);
            }
        });

        jlabelQuantidade.setText("Preço de Venda");

        jlabelColecao.setText("*Descrição:");

        jlabelSexo.setText("*Data");

        butCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        butCadastrar.setText("Cadastrar");
        butCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCadastrarActionPerformed(evt);
            }
        });

        butAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book_edit.png"))); // NOI18N
        butAlterar.setText("Alterar");
        butAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAlterarActionPerformed(evt);
            }
        });

        butExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        butExcluir.setText("Excluir");
        butExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExcluirActionPerformed(evt);
            }
        });

        botaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("*Preço de Compra:");

        jlabelQuantidade1.setText("*Quantidade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabelNome)
                            .addComponent(jlabelQuantidade)
                            .addComponent(jLabel2)
                            .addComponent(jlabelColecao))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(precoText, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(qtdText2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlabelQuantidade1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(qtdText1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jlabelSexo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qtdText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(qtdText3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addComponent(nomeText, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCancelar)
                        .addGap(115, 115, 115)
                        .addComponent(butCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelNome)
                    .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelColecao)
                    .addComponent(qtdText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(precoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qtdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlabelSexo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelQuantidade1)
                    .addComponent(jlabelQuantidade)
                    .addComponent(qtdText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtdText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCadastrar)
                    .addComponent(butAlterar)
                    .addComponent(butExcluir)
                    .addComponent(botaoCancelar))
                .addContainerGap())
        );

        botaoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoBuscar)
                .addGap(101, 101, 101))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(botaoBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        // chama tela buscaProduto:
        ProductSearch dlg = new ProductSearch(this, true);
        prod = dlg.selecionarProduto();
        if (prod!=null) {
            nomeText.setText(prod.getNome());
            qtdText.setText(Integer.toString(prod.getQuantidade()));
            precoText.setText(Double.toString(prod.getPreco()));
            boxColecao.setSelectedItem(prod.getColecao());
            boxCor.setSelectedItem(prod.getCor());
            boxSexo.setSelectedItem(prod.getSexo());
            boxTamanho.setSelectedItem(prod.getTamanho());
            butCadastrar.setVisible(false);
            butAlterar.setVisible(true);
            butExcluir.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Produto não selecionado!");
        }
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        // ativa botão de Cancelar:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void butExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExcluirActionPerformed
        // TODO add your handling code here:
        int escolha = JOptionPane.showOptionDialog(null, "Deseja excluir o cadastro?", "Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (escolha == JOptionPane.YES_OPTION) {
            try {
                Servico.ServicoProduto.excluirProduto(prod.getID());
            } catch (ProdutoException e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
                return;
            } catch (DataSourceException e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
                return;
            }
            JOptionPane.showMessageDialog(rootPane, "Produto excluído com sucesso");
            butCadastrar.setVisible(true);
            butAlterar.setVisible(false);
            butExcluir.setVisible(false);
            nomeText.setText("");
            qtdText.setText("");
            precoText.setText("");
            boxColecao.setSelectedItem("Selecione");
            boxCor.setSelectedItem("Selecione");
            boxSexo.setSelectedItem("Selecione");
            boxTamanho.setSelectedItem("Selecione");
        }
    }//GEN-LAST:event_butExcluirActionPerformed

    private void butCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCadastrarActionPerformed
        // TODO add your handling code here:
        prod = new Produto();
        String o = boxColecao.getSelectedItem().toString();
            if (o.compareTo("Selecione")==0) {
                prod.setColecao("");
            }else{
                prod.setColecao((String)boxColecao.getSelectedItem());
            }
        String o1 = boxCor.getSelectedItem().toString();
            if (o1.compareTo("Selecione")==0) {
                prod.setCor("");
            }else{
                prod.setCor((String)boxCor.getSelectedItem());
            }
        prod.setNome(nomeText.getText());
        prod.setPreco(Double.parseDouble(precoText.getText()));
        prod.setQuantidade(Integer.parseInt(qtdText.getText()));
        String o2 = boxSexo.getSelectedItem().toString();
            if (o2.compareTo("Selecione")==0) {
                prod.setSexo("");
            }else{
                prod.setSexo((String)boxSexo.getSelectedItem());
            }
        String o3 = boxTamanho.getSelectedItem().toString();
            if (o3.compareTo("Selecione")==0) {
                prod.setTamanho("");
            }else{
                prod.setTamanho((String)boxTamanho.getSelectedItem());
            }
        try {
            Servico.ServicoProduto.cadastrarProduto(prod);
        } catch (ProdutoException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            return;
        } catch (DataSourceException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            return;
        }
        JOptionPane.showMessageDialog(rootPane, "Produto adicionado com sucesso");
        butCadastrar.setVisible(true);
        butAlterar.setVisible(false);
        butExcluir.setVisible(false);
        nomeText.setText("");
        qtdText.setText("");
        precoText.setText("");
        boxColecao.setSelectedItem("Selecione");
        boxCor.setSelectedItem("Selecione");
        boxSexo.setSelectedItem("Selecione");
        boxTamanho.setSelectedItem("Selecione");
    }//GEN-LAST:event_butCadastrarActionPerformed

    private void butAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAlterarActionPerformed
        // TODO add your handling code here:
        String o = boxColecao.getSelectedItem().toString();
            if (o.compareTo("Selecione")==0) {
                prod.setColecao("");
            }else{
                prod.setColecao((String)boxColecao.getSelectedItem());
            }
        String o1 = boxCor.getSelectedItem().toString();
            if (o1.compareTo("Selecione")==0) {
                prod.setCor("");
            }else{
                prod.setCor((String)boxCor.getSelectedItem());
            }
        prod.setNome(nomeText.getText());
        prod.setPreco(Double.parseDouble(precoText.getText()));
        prod.setQuantidade(Integer.parseInt(qtdText.getText()));
        String o2 = boxSexo.getSelectedItem().toString();
            if (o2.compareTo("Selecione")==0) {
                prod.setSexo("");
            }else{
                prod.setSexo((String)boxSexo.getSelectedItem());
            }
        String o3 = boxTamanho.getSelectedItem().toString();
            if (o3.compareTo("Selecione")==0) {
                prod.setTamanho("");
            }else{
                prod.setTamanho((String)boxTamanho.getSelectedItem());
            }
        try {
            Servico.ServicoProduto.atualizarProduto(prod, prod.getID());
        } catch (ProdutoException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            return;
        } catch (DataSourceException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            return;
        }
        JOptionPane.showMessageDialog(rootPane, "Produto Alterado Com Sucesso");
        butCadastrar.setVisible(true);
        butAlterar.setVisible(false);
        butExcluir.setVisible(false);
        nomeText.setText("");
        qtdText.setText("");
        precoText.setText("");
        boxColecao.setSelectedItem("Selecione");
        boxCor.setSelectedItem("Selecione");
        boxSexo.setSelectedItem("Selecione");
        boxTamanho.setSelectedItem("Selecione");
    }//GEN-LAST:event_butAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton butAlterar;
    private javax.swing.JButton butCadastrar;
    private javax.swing.JButton butExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabelColecao;
    private javax.swing.JLabel jlabelNome;
    private javax.swing.JLabel jlabelQuantidade;
    private javax.swing.JLabel jlabelQuantidade1;
    private javax.swing.JLabel jlabelSexo;
    private javax.swing.JTextField nomeText;
    private javax.swing.JTextField precoText;
    private javax.swing.JTextField qtdText;
    private javax.swing.JTextField qtdText1;
    private javax.swing.JTextField qtdText2;
    private javax.swing.JTextField qtdText3;
    // End of variables declaration//GEN-END:variables


    public static void main(String args[]) throws Exception {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductMain().setVisible(true);
            }
        });
    }


}
